<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ucpp</string>
		<string>uh</string>
	</array>
	<key>name</key>
	<string>uC++</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.c++</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.ucpp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ucpp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((and|or)\s+)?(_When|_Accept|_Select|_Timeout)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(_Coroutine|_Monitor|_Cormonitor|_PeriodicTask|_RealTimeTask|_SporadicTask|_Task|_Event)\b</string>
			<key>name</key>
			<string>storage.type.ucpp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(_At|_CatchResume|_Finally|_Disable|_Enable|_Resume|_Throw|_Else)\b</string>
			<key>name</key>
			<string>keyword.control.ucpp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(_Mutex|_Nomutex)\b</string>
			<key>name</key>
			<string>storage.modifier.ucpp</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ucpp</string>
	<key>uuid</key>
	<string>6d5872a5-0367-4387-af71-8f4102f198f0</string>
</dict>
</plist>
